language: node_js
sudo: required
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn build
  - ./deploy.sh
branch: master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"